### ISSUE TITLE
Meteor React Package vs Npm React

### ISSUE THREAD

**Issue by ccorcos** [JeremyBYU/meteor-import#1]
I thought the point of the new 1.3 modules stuff is that I could just use the npm React :'(

**Comment by JeremyBYU** [comment]
I think it will be able to once 1.3 is fully released.  It looks like it just needs to be wrapped with a bundler (like browserify or webpack).  I think I read something somewhere where a meteor member was saying they were working on this.

**Comment by ccorcos** [comment]
sweet!
