### ISSUE TITLE
Uncaught Error: Cannot find module '../../node_modules/formsy-react'

### ISSUE THREAD

**Issue by mbrookes** [JeremyBYU/meteor-import#2]
I had to change line 1 in `client/imports/mmform.jsx` to:

```
let Formsy = require('formsy-react'); 
```

Oddly, I didn't have to change `client/imports/mmform.jsx` - no error and the form works, but it still works when I take out the relative path.

This is with the same versions as you, as I just did:

```
git clone https://github.com/JeremyBYU/meteor-import.git
cd meteor-import
npm install
meteor
```

**Comment by JeremyBYU** [comment]
Thanks, I'll try it out on my computer.  What version of 1.3 beta are you using?

**Comment by mbrookes** [comment]
Same version as you (the version is specified in `.meteor/versions`) - I didn't upgrade before testing. I've since upgraded to the current beta, and it still works fine. 

Odd though that I only get the error for one file and not the other...

I also had to switch to NPM react, not the package version for some reason.
